export default [{ "_id": "US", "name": "United States" },
      { "_id": "AF", "name": "Afghanistan" },
      { "_id": "AX", "name": "Åland Islands" },
      { "_id": "AL", "name": "Albania" },
      { "_id": "DZ", "name": "Algeria" },
      { "_id": "AS", "name": "American Samoa" },
      { "_id": "AD", "name": "Andorra" },
      { "_id": "AO", "name": "Angola" },
      { "_id": "AI", "name": "Anguilla" },
      { "_id": "AQ", "name": "Antarctica" },
      { "_id": "AG", "name": "Antigua and Barbuda" },
      { "_id": "AR", "name": "Argentina" },
      { "_id": "AM", "name": "Armenia" },
      { "_id": "AW", "name": "Aruba" },
      { "_id": "AU", "name": "Australia" },
      { "_id": "AT", "name": "Austria" },
      { "_id": "AZ", "name": "Azerbaijan" },
      { "_id": "BS", "name": "Bahamas" },
      { "_id": "BH", "name": "Bahrain" },
      { "_id": "BD", "name": "Bangladesh" },
      { "_id": "BB", "name": "Barbados" },
      { "_id": "BY", "name": "Belarus" },
      { "_id": "BE", "name": "Belgium" },
      { "_id": "BZ", "name": "Belize" },
      { "_id": "BJ", "name": "Benin" },
      { "_id": "BM", "name": "Bermuda" },
      { "_id": "BT", "name": "Bhutan" },
      { "_id": "BO", "name": "Bolivia, Plurinational State of" },
      { "_id": "BQ", "name": "Bonaire, Sint Eustatius and Saba" },
      { "_id": "BA", "name": "Bosnia and Herzegovina" },
      { "_id": "BW", "name": "Botswana" },
      { "_id": "BV", "name": "Bouvet Island" },
      { "_id": "BR", "name": "Brazil" },
      { "_id": "IO", "name": "British Indian Ocean Territory" },
      { "_id": "BN", "name": "Brunei Darussalam" },
      { "_id": "BG", "name": "Bulgaria" },
      { "_id": "BF", "name": "Burkina Faso" },
      { "_id": "BI", "name": "Burundi" },
      { "_id": "KH", "name": "Cambodia" },
      { "_id": "CM", "name": "Cameroon" },
      { "_id": "CA", "name": "Canada" },
      { "_id": "CV", "name": "Cape Verde" },
      { "_id": "KY", "name": "Cayman Islands" },
      { "_id": "CF", "name": "Central African Republic" },
      { "_id": "TD", "name": "Chad" },
      { "_id": "CL", "name": "Chile" },
      { "_id": "CN", "name": "China" },
      { "_id": "CX", "name": "Christmas Island" },
      { "_id": "CC", "name": "Cocos (Keeling) Islands" },
      { "_id": "CO", "name": "Colombia" },
      { "_id": "KM", "name": "Comoros" },
      { "_id": "CG", "name": "Congo" },
      { "_id": "CD", "name": "Congo, the Democratic Republic of the" },
      { "_id": "CK", "name": "Cook Islands" },
      { "_id": "CR", "name": "Costa Rica" },
      { "_id": "CI", "name": "Côte d'Ivoire" },
      { "_id": "HR", "name": "Croatia" },
      { "_id": "CU", "name": "Cuba" },
      { "_id": "CW", "name": "Curaçao" },
      { "_id": "CY", "name": "Cyprus" },
      { "_id": "CZ", "name": "Czech Republic" },
      { "_id": "DK", "name": "Denmark" },
      { "_id": "DJ", "name": "Djibouti" },
      { "_id": "DM", "name": "Dominica" },
      { "_id": "DO", "name": "Dominican Republic" },
      { "_id": "EC", "name": "Ecuador" },
      { "_id": "EG", "name": "Egypt" },
      { "_id": "SV", "name": "El Salvador" },
      { "_id": "GQ", "name": "Equatorial Guinea" },
      { "_id": "ER", "name": "Eritrea" },
      { "_id": "EE", "name": "Estonia" },
      { "_id": "ET", "name": "Ethiopia" },
      { "_id": "FK", "name": "Falkland Islands (Malvinas)" },
      { "_id": "FO", "name": "Faroe Islands" },
      { "_id": "FJ", "name": "Fiji" },
      { "_id": "FI", "name": "Finland" },
      { "_id": "FR", "name": "France" },
      { "_id": "GF", "name": "French Guiana" },
      { "_id": "PF", "name": "French Polynesia" },
      { "_id": "TF", "name": "French Southern Territories" },
      { "_id": "GA", "name": "Gabon" },
      { "_id": "GM", "name": "Gambia" },
      { "_id": "GE", "name": "Georgia" },
      { "_id": "DE", "name": "Germany" },
      { "_id": "GH", "name": "Ghana" },
      { "_id": "GI", "name": "Gibraltar" },
      { "_id": "GR", "name": "Greece" },
      { "_id": "GL", "name": "Greenland" },
      { "_id": "GD", "name": "Grenada" },
      { "_id": "GP", "name": "Guadeloupe" },
      { "_id": "GU", "name": "Guam" },
      { "_id": "GT", "name": "Guatemala" },
      { "_id": "GG", "name": "Guernsey" },
      { "_id": "GN", "name": "Guinea" },
      { "_id": "GW", "name": "Guinea-Bissau" },
      { "_id": "GY", "name": "Guyana" },
      { "_id": "HT", "name": "Haiti" },
      { "_id": "HM", "name": "Heard Island and McDonald Mcdonald Islands" },
      { "_id": "VA", "name": "Holy See (Vatican City State)" },
      { "_id": "HN", "name": "Honduras" },
      { "_id": "HK", "name": "Hong Kong" },
      { "_id": "HU", "name": "Hungary" },
      { "_id": "IS", "name": "Iceland" },
      { "_id": "IN", "name": "India" },
      { "_id": "ID", "name": "Indonesia" },
      { "_id": "IR", "name": "Iran, Islamic Republic of" },
      { "_id": "IQ", "name": "Iraq" },
      { "_id": "IE", "name": "Ireland" },
      { "_id": "IM", "name": "Isle of Man" },
      { "_id": "IL", "name": "Israel" },
      { "_id": "IT", "name": "Italy" },
      { "_id": "JM", "name": "Jamaica" },
      { "_id": "JP", "name": "Japan" },
      { "_id": "JE", "name": "Jersey" },
      { "_id": "JO", "name": "Jordan" },
      { "_id": "KZ", "name": "Kazakhstan" },
      { "_id": "KE", "name": "Kenya" },
      { "_id": "KI", "name": "Kiribati" },
      { "_id": "KP", "name": "Korea, Democratic People's Republic of" },
      { "_id": "KR", "name": "Korea, Republic of" },
      { "_id": "KW", "name": "Kuwait" },
      { "_id": "KG", "name": "Kyrgyzstan" },
      { "_id": "LA", "name": "Lao People's Democratic Republic" },
      { "_id": "LV", "name": "Latvia" },
      { "_id": "LB", "name": "Lebanon" },
      { "_id": "LS", "name": "Lesotho" },
      { "_id": "LR", "name": "Liberia" },
      { "_id": "LY", "name": "Libya" },
      { "_id": "LI", "name": "Liechtenstein" },
      { "_id": "LT", "name": "Lithuania" },
      { "_id": "LU", "name": "Luxembourg" },
      { "_id": "MO", "name": "Macao" },
      { "_id": "MK", "name": "Macedonia, the Former Yugoslav Republic of" },
      { "_id": "MG", "name": "Madagascar" },
      { "_id": "MW", "name": "Malawi" },
      { "_id": "MY", "name": "Malaysia" },
      { "_id": "MV", "name": "Maldives" },
      { "_id": "ML", "name": "Mali" },
      { "_id": "MT", "name": "Malta" },
      { "_id": "MH", "name": "Marshall Islands" },
      { "_id": "MQ", "name": "Martinique" },
      { "_id": "MR", "name": "Mauritania" },
      { "_id": "MU", "name": "Mauritius" },
      { "_id": "YT", "name": "Mayotte" },
      { "_id": "MX", "name": "Mexico" },
      { "_id": "FM", "name": "Micronesia, Federated States of" },
      { "_id": "MD", "name": "Moldova, Republic of" },
      { "_id": "MC", "name": "Monaco" },
      { "_id": "MN", "name": "Mongolia" },
      { "_id": "ME", "name": "Montenegro" },
      { "_id": "MS", "name": "Montserrat" },
      { "_id": "MA", "name": "Morocco" },
      { "_id": "MZ", "name": "Mozambique" },
      { "_id": "MM", "name": "Myanmar" },
      { "_id": "NA", "name": "Namibia" },
      { "_id": "NR", "name": "Nauru" },
      { "_id": "NP", "name": "Nepal" },
      { "_id": "NL", "name": "Netherlands" },
      { "_id": "NC", "name": "New Caledonia" },
      { "_id": "NZ", "name": "New Zealand" },
      { "_id": "NI", "name": "Nicaragua" },
      { "_id": "NE", "name": "Niger" },
      { "_id": "NG", "name": "Nigeria" },
      { "_id": "NU", "name": "Niue" },
      { "_id": "NF", "name": "Norfolk Island" },
      { "_id": "MP", "name": "Northern Mariana Islands" },
      { "_id": "NO", "name": "Norway" },
      { "_id": "OM", "name": "Oman" },
      { "_id": "PK", "name": "Pakistan" },
      { "_id": "PW", "name": "Palau" },
      { "_id": "PS", "name": "Palestine, State of" },
      { "_id": "PA", "name": "Panama" },
      { "_id": "PG", "name": "Papua New Guinea" },
      { "_id": "PY", "name": "Paraguay" },
      { "_id": "PE", "name": "Peru" },
      { "_id": "PH", "name": "Philippines" },
      { "_id": "PN", "name": "Pitcairn" },
      { "_id": "PL", "name": "Poland" },
      { "_id": "PT", "name": "Portugal" },
      { "_id": "PR", "name": "Puerto Rico" },
      { "_id": "QA", "name": "Qatar" },
      { "_id": "RE", "name": "Réunion" },
      { "_id": "RO", "name": "Romania" },
      { "_id": "RU", "name": "Russian Federation" },
      { "_id": "RW", "name": "Rwanda" },
      { "_id": "BL", "name": "Saint Barthélemy" },
      { "_id": "SH", "name": "Saint Helena, Ascension and Tristan da Cunha" },
      { "_id": "KN", "name": "Saint Kitts and Nevis" },
      { "_id": "LC", "name": "Saint Lucia" },
      { "_id": "MF", "name": "Saint Martin (French part)" },
      { "_id": "PM", "name": "Saint Pierre and Miquelon" },
      { "_id": "VC", "name": "Saint Vincent and the Grenadines" },
      { "_id": "WS", "name": "Samoa" },
      { "_id": "SM", "name": "San Marino" },
      { "_id": "ST", "name": "Sao Tome and Principe" },
      { "_id": "SA", "name": "Saudi Arabia" },
      { "_id": "SN", "name": "Senegal" },
      { "_id": "RS", "name": "Serbia" },
      { "_id": "SC", "name": "Seychelles" },
      { "_id": "SL", "name": "Sierra Leone" },
      { "_id": "SG", "name": "Singapore" },
      { "_id": "SX", "name": "Sint Maarten (Dutch part)" },
      { "_id": "SK", "name": "Slovakia" },
      { "_id": "SI", "name": "Slovenia" },
      { "_id": "SB", "name": "Solomon Islands" },
      { "_id": "SO", "name": "Somalia" },
      { "_id": "ZA", "name": "South Africa" },
      { "_id": "GS", "name": "South Georgia and the South Sandwich Islands" },
      { "_id": "SS", "name": "South Sudan" },
      { "_id": "ES", "name": "Spain" },
      { "_id": "LK", "name": "Sri Lanka" },
      { "_id": "SD", "name": "Sudan" },
      { "_id": "SR", "name": "Suriname" },
      { "_id": "SJ", "name": "Svalbard and Jan Mayen" },
      { "_id": "SZ", "name": "Swaziland" },
      { "_id": "SE", "name": "Sweden" },
      { "_id": "CH", "name": "Switzerland" },
      { "_id": "SY", "name": "Syrian Arab Republic" },
      { "_id": "TW", "name": "Taiwan, Province of China" },
      { "_id": "TJ", "name": "Tajikistan" },
      { "_id": "TZ", "name": "Tanzania, United Republic of" },
      { "_id": "TH", "name": "Thailand" },
      { "_id": "TL", "name": "Timor-Leste" },
      { "_id": "TG", "name": "Togo" },
      { "_id": "TK", "name": "Tokelau" },
      { "_id": "TO", "name": "Tonga" },
      { "_id": "TT", "name": "Trinidad and Tobago" },
      { "_id": "TN", "name": "Tunisia" },
      { "_id": "TR", "name": "Turkey" },
      { "_id": "TM", "name": "Turkmenistan" },
      { "_id": "TC", "name": "Turks and Caicos Islands" },
      { "_id": "TV", "name": "Tuvalu" },
      { "_id": "UG", "name": "Uganda" },
      { "_id": "UA", "name": "Ukraine" },
      { "_id": "AE", "name": "United Arab Emirates" },
      { "_id": "GB", "name": "United Kingdom" },
      { "_id": "UM", "name": "United States Minor Outlying Islands" },
      { "_id": "UY", "name": "Uruguay" },
      { "_id": "UZ", "name": "Uzbekistan" },
      { "_id": "VU", "name": "Vanuatu" },
      { "_id": "VE", "name": "Venezuela, Bolivarian Republic of" },
      { "_id": "VN", "name": "Viet Nam" },
      { "_id": "VG", "name": "Virgin Islands, British" },
      { "_id": "VI", "name": "Virgin Islands, U.S." },
      { "_id": "WF", "name": "Wallis and Futuna" },
      { "_id": "EH", "name": "Western Sahara" },
      { "_id": "YE", "name": "Yemen" },
      { "_id": "ZM", "name": "Zambia" },
      { "_id": "ZW", "name": "Zimbabwe" }
    ];